### PR TITLE
Update toast outlines for persistent toasts

### PR DESCRIPTION
**Pull request by louisescher**
#### Description

- Improves toasts by adding an outline to persistent toasts, which were barely visible due to not having a colored progress bar.

image

### CODE REVIEW

**Comment by studiocms-no-reply** [comment]
Thank you for submitting your Pull Request, the following links will become available for preview shortly:


  - [StudioCMS Landing Page](https://pr371.www.studiocms.xyz/)

  - [StudioCMS Documentation](https://pr371.docs.studiocms.xyz/)

  - [StudioCMS Demo (node-playground)](https://pr371.demo.studiocms.xyz/) (Also deployed with package changes)

  - [StudioCMS Ui Demo (ui-playground)](https://pr371.ui-testing.studiocms.xyz/)

**Review by TheOtterlord — APPROVED** [review]
looks great!

**Review by JusticeMatthew — COMMENTED** [review]
Looks good to me

Nice catch too, that's a very common accessibility miss (not using a border for separation when the BG of the two elements doesn't have enough contrast)

**Comment by studiocms-no-reply** [comment]
Thank you for submitting your Pull Request, the following links will become available for preview shortly:


  - [StudioCMS Landing Page](https://pr371.www.studiocms.xyz/)

  - [StudioCMS Documentation](https://pr371.docs.studiocms.xyz/)

  - [StudioCMS Demo (node-playground)](https://pr371.demo.studiocms.xyz/) (Also deployed with package changes)

  - [StudioCMS Ui Demo (ui-playground)](https://pr371.ui-testing.studiocms.xyz/)

**Review by dreyfus92 — APPROVED** [review]
Thank you @louisescher 😁

**Review by Adammatthiesen — APPROVED** [review]

**Pull request merged**
