### PR TITLE
Auth Overhaul

### LINKED ISSUE #326: New Login Page

### LINKED ISSUE #327: Update Permissions system with new `"owner"` rank

### PR DESCRIPTION
**Pull request by Adammatthiesen**
Closes #327
Closes #326

Partial #73
Partial #331

This pull request includes a comprehensive overhaul of the authentication system in the StudioCMS project, along with updates to dependencies and refactoring of various components. The most important changes include the introduction of new environment variables, removal of the old authentication system, addition of new components, updates to database schemas, and refactoring of dependencies in multiple packages.

### Auth System Overhaul:
* **Environment Variables**: Added `CMS_ENCRYPTION_KEY` and `CMS_GITHUB_REDIRECT_URI` to the `astro:env` schema for authentication purposes. [[1]](diffhunk://#diff-fdec1e74e25a19bd534e12503829d18d0274e1812fec0c4289cd2c39e5ca5abaR7-R12) [[2]](diffhunk://#diff-fdec1e74e25a19bd534e12503829d18d0274e1812fec0c4289cd2c39e5ca5abaR24-R28)
* **Components**: Introduced new `OAuthButton`, `OAuthButtonStack`, and `AuthLayout` components, along with their associated CSS and scripts. [[1]](diffhunk://#diff-a98d0889d02b0e7cde61110170024ebe68f92d82397a9ae285c386ed6266fd04R1-R21) [[2]](diffhunk://#diff-7af97f6d6660e264fb72251e1123530fb10a0bfd7e78bb539544ab052922f314R1-R11) [[3]](diffhunk://#diff-62adb6782272c5d0543f1092522b1431c8daee1951887a8a75d694e2ae69d506R1-R57)
* **Removal of Old System**: Removed the `Lucia` based authentication system and associated files (`lucia-astrodb-adapter`, `authHelper`). [[1]](diffhunk://#diff-59bbb798598dccdeb2640f5bc2173d9706742718b5c696f809462033e5484ff8L1-L33) [[2]](diffhunk://#diff-6ce6c7adb9436769ecbb6c04d46780bfcefd4818673ef72cd19872157098f668L1-L179)
* **Database Schema Updates**: Updated `StudioCMSUsers` table to remove OAuth IDs, added `StudioCMSOAuthAccounts` table for handling OAuth accounts, and updated `StudioCMSPermissions` and `StudioCMSSiteConfig` tables.

### Dependency and Configuration Updates:
* **Dependency Updates**: Updated dependencies in `package.json` files across multiple packages (`@studiocms/auth`, `@studiocms/core`, `@studiocms/dashboard`, `@studiocms/ui`). [[1]](diffhunk://#diff-2d16107b635fed3f93e32a31b7351ed4af23aa3e9b5de69af9992939bbb41c38L46-L53) [[2]](diffhunk://#diff-2d16107b635fed3f93e32a31b7351ed4af23aa3e9b5de69af9992939bbb41c38L63-R95) [[3]](diffhunk://#diff-2d16107b635fed3f93e32a31b7351ed4af23aa3e9b5de69af9992939bbb41c38L95) [[4]](diffhunk://#diff-7dce3f5411a64e41df908116a0fe349038fb679a57f353e69ba8bc6362220e36L33-R59)
* **Configuration Changes**: Updated `biome.json` to adjust the list of ignored files.

These changes collectively aim to enhance the security, maintainability, and functionality of the StudioCMS authentication system.

### CODE REVIEW

**Comment by studiocms-no-reply** [comment]
Thank you for submitting your Pull Request, the following links will become available for preview shortly:


  - [StudioCMS Landing Page](https://pr369.www.studiocms.xyz/)

  - [StudioCMS Documentation](https://pr369.docs.studiocms.xyz/)

  - [StudioCMS Demo (node-playground)](https://pr369.demo.studiocms.xyz/) (Also deployed with package changes)

  - [StudioCMS Ui Demo (ui-playground)](https://pr369.ui-testing.studiocms.xyz/)

**Comment by Adammatthiesen** [comment]
Demo for new login page (and auth system) is available at https://next-demo.studiocms.xyz/dashboard/login

oAuth is currently disabled due to other requirements for oAuth not being done yet(Dashboard stuff that will happen as part of the redesign)

**Review by louisescher — APPROVED** [review]
*lgtm*

**Review by dreyfus92 — APPROVED** [review]
Massive refactor 🚢

**Pull request merged**
